# Generated by Django 3.2.7 on 2021-09-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Piece', 'Piece')], default='Select Quantity', max_length=20),
        ),
    ]
